// 画面文言はすべてここに集約する（CLAUDE.md「文字列リテラルは設定ファイルに分離する」）。
// ハードコード検出テスト（test/unit/noHardcodedStringsFrontend.test.ts）はこのファイル以外の
// 日本語リテラルを src/frontend 配下で検出する。ですます調で統一する。

export const STRINGS = {
  app: {
    title: "受託業務標準フローテンプレート（デモ版）",
    dataLifetimeNotice: "登録した案件は日次リセット（JST 03:00）により当日限りで消去されます。",
  },
  nav: {
    profileInput: "プロファイル入力",
    flowOverview: "フロー全体図",
    changeRequest: "変更要求",
    history: "履歴",
  },
  profileInput: {
    heading: "案件プロファイルの入力",
    labelFieldLabel: "案件ラベル（任意）",
    labelFieldNotice: "実在の顧客名・個人名を含めないでください。",
    labelPlaceholder: "例：デモ案件A",
    contractType: "契約形態",
    workType: "業務種別",
    scale: "規模",
    requirementCertainty: "要件確定度",
    previewButton: "展開プレビューを表示",
    registerButton: "この内容で登録する",
    previewHeading: "展開プレビュー",
    previewPhaseColumn: "工程",
    previewGateColumn: "ゲート種別",
    rejectedHeading: "登録できません",
    warningHeading: "警告",
    recommendationPrefix: "推奨：",
    noPreviewYet: "契約形態・業務種別・規模・要件確定度を選び、「展開プレビューを表示」を押してください。",
  },
  contractTypeOptions: {
    請負: "請負",
    準委任: "準委任",
    ハイブリッド: "ハイブリッド",
  },
  workTypeOptions: {
    新規開発: "新規開発",
    改修: "改修",
    保守運用: "保守運用",
    調査: "調査（PoCを含む）",
  },
  scaleOptions: {
    小: "小",
    中: "中",
    大: "大",
  },
  certaintyOptions: {
    確定: "確定",
    未確定: "未確定",
  },
  flowOverview: {
    heading: "フロー全体図",
    currentPhaseLabel: "現工程",
    contractSegmentLabel: "契約区間",
    warningsHeading: "登録時の警告",
    carryoverCountLabel: "未解決の持越し課題",
    changeRequestCountLabel: "未合意の変更要求",
    deliverableProgressLabel: "必須成果物",
    criterionProgressLabel: "判断基準",
    appliedRulesLabel: "適用規則",
    noProjectSelected: "案件が選択されていません。プロファイル入力から登録してください。",
    openPhaseButton: "工程詳細を開く",
  },
  phaseDetail: {
    heading: "工程詳細",
    deliverablesHeading: "成果物",
    criteriaHeading: "判断基準",
    approvalsHeading: "承認記録",
    gateHeading: "ゲート評価",
    transitionHeading: "遷移操作",
    maintenanceHeading: "保守運用サイクル",
    requirementRequired: "必須",
    requirementOptional: "任意",
    levelRequired: "必須",
    levelRecommended: "推奨",
    autoAttachedBadge: "自動付与",
    recurringBadge: "反復",
    satisfiedLabel: "達成",
    unsatisfiedLabel: "未達",
    addApprovalButton: "承認記録を追加",
    approverRoleLabel: "承認ロール",
    approvedOnLabel: "承認日",
    evaluateButton: "ゲートを判定する",
    verdictPass: "通過",
    verdictConditional: "条件付き通過",
    verdictFail: "不通過",
    unmetRequiredHeading: "未達の必須基準",
    unmetRecommendedHeading: "未達の推奨基準（持越し課題として登録されます）",
    advanceButton: "前進する",
    rollbackButton: "差戻しする",
    abortButton: "案件を中止する",
    rollbackDialogTitle: "差戻し",
    rollbackTargetLabel: "差戻し先の工程",
    rollbackReasonLabel: "理由",
    abortDialogTitle: "案件の中止",
    abortReasonLabel: "理由",
    maintenanceStartButton: "周期を開始する",
    maintenanceStageLabel: "現在の段階",
    maintenanceAdvanceStageButton: "次の段階へ進める",
    maintenanceRecordSummaryLabel: "保守対応の概要",
    maintenanceRecordAddButton: "保守対応記録を追加する",
    maintenanceCompleteCycleButton: "周期を完了する",
    maintenanceRecordsHeading: "保守対応記録一覧",
    noMaintenanceCycle: "進行中の周期がありません。",
    carryoverHeading: "持越し課題",
    carryoverResolveButton: "この工程で解決する",
    noPhaseSelected: "工程が選択されていません。フロー全体図から工程を選んでください。",
  },
  changeRequest: {
    heading: "変更要求",
    listHeading: "一覧",
    raiseHeading: "起票",
    titleLabel: "変更内容",
    raiseButton: "起票する",
    impactHeading: "影響評価",
    affectsEffortLabel: "工数への影響がある",
    affectsScheduleLabel: "納期への影響がある",
    affectsCostLabel: "金額への影響がある",
    impactDeliverablesLabel: "影響を受ける成果物",
    saveImpactButton: "影響評価を保存する",
    agreementHeading: "合意",
    agreeButton: "合意する",
    rejectButton: "却下する",
    rejectReasonLabel: "却下理由",
    amendmentNotice: "請負区間で金額・納期に影響があるため、契約締結（P03）に契約変更覚書が必須成果物として追加されます。",
    state起票: "起票",
    state影響評価中: "影響評価中",
    state合意待ち: "合意待ち",
    state反映済: "反映済",
    state却下: "却下",
    noProjectSelected: "案件が選択されていません。",
  },
  history: {
    heading: "履歴",
    transitionsHeading: "遷移履歴",
    gateReviewsHeading: "判定履歴",
    changeRequestsHeading: "変更要求履歴",
    noProjectSelected: "案件が選択されていません。",
  },
  dialog: {
    confirmLabel: "実行する",
    cancelLabel: "キャンセル",
  },
  common: {
    loading: "読み込み中です…",
    save: "保存する",
    close: "閉じる",
    error: "エラーが発生しました。",
  },
  demo: {
    banner: "これはデモ版です。データはサーバー再起動時にリセットされる場合があります。",
    backToList: "← デモ一覧へ",
    consult: "ご相談はこちら",
    legalLink: "利用規約・免責事項・連絡先",
    copyright: "© 2026 Ricta Works",
  },
  legal: {
    title: "利用規約・免責事項・連絡先",
    backToApp: "← デモに戻る",
    termsHeading: "利用規約",
    terms: [
      "本サービスは受託業務標準フローテンプレートの体験用デモ版です。実際の契約・案件管理業務での利用を目的としたものではありません。",
      "登録した案件プロファイル・工程・成果物・判断基準等のデータは、サーバー再起動または日次リセット（JST 03:00）により消去される場合があります。継続利用が必要なデータの保存先としては使用しないでください。",
      "案件ラベル等の入力欄に実在する顧客名・個人名・機密情報を入力しないでください。",
      "本サービスの内容は予告なく変更・停止することがあります。",
    ],
    disclaimerHeading: "免責事項",
    disclaimer: [
      "本サービスで導出される工程・成果物・判断基準・ゲート判定は、あらかじめ定めた規則（R01〜R17）による機械的な導出結果であり、実際の契約実務における法的助言・専門的判断に代わるものではありません。",
      "本サービスの利用により生じたいかなる損害についても、運営者は責任を負いません。",
    ],
    contactHeading: "連絡先",
    contact: {
      brand: "屋号",
      brandValue: "Ricta Works",
      address: "住所",
      addressValue: "〒190-0022 東京都立川市錦町1丁目4-20 TSCビル5階",
      phone: "電話",
      phoneValue: "070-5148-0380",
      email: "メール",
      emailValue: "info@rictaworks.jp",
      web: "Web",
      webValue: "https://rictaworks.jp",
      x: "X",
      xValue: "@rictaworks",
      github: "GitHub",
      githubValue: "github.com/rictaworks",
    },
  },
} as const;
